version: '3'
services:
    psql:
        image: postgres
        ports:
            - '5432'
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
    php:
        build: php-fpm
        ports:
            - '9002:9000'
        volumes:
            - ../:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/logs:cached
        links:
            - psql
    nginx:
        build: nginx
        ports:
            - '8080:80'
        links:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached
